AWSTemplateFormatVersion: 2010-09-09
Description: Create a website hosted in S3
Parameters:
  s3BucketName:
    Description: S3 bucket name
    Type: String
    Default: ""

Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref s3BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: env
          Value: dev
Outputs:
  WebSiteURL:
    Value: !GetAtt
      - s3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
    

